# Generated by Django 6.0 on 2026-02-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Blog',
            new_name='blog',
        ),
    ]
