# Generated by Django 6.0 on 2026-02-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bod',
            new_name='dob',
        ),
    ]
